# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vercel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and ci and build
      env:
        REACT_APP_API_KEY_CROWDIN: ${{ secrets.API_KEY_CROWDIN }}
        REACT_APP_API_KEY_GITHUB: ${{ secrets.API_KEY_GITHUB }}
      run: |
        npm install
        npm ci
        npm run build
        mkdir build
        mv out functions
        cp -R public build
        cp -R functions build
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  # https://github.com/marketplace/actions/vercel-action
  # https://github.com/vercel/vercel/discussions/4367#discussioncomment-1672222
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          # vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          working-directory: ./functions
